package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {

    //根据商品id和用户id查询用户是否添加过该商品，数据库中是否有该商品的购物车
    Cart findByProductIdAndUserId(@Param("productId")Integer productId,
                                  @Param("userId")Integer userId);
    //根据用户id查找
    List<Cart> findByUserId(Integer userId);
    //删除商品
    int deleteProduct(@Param("productIdList")List<Integer> productIdList,
                      @Param("userId")Integer userId);
    //选中商品
    int checkedProduct(@Param("productId")Integer productId,
                       @Param("userId")Integer userId);
    //取消选中商品
    int uncheckedProduct(@Param("productId")Integer productId,
                         @Param("userId")Integer userId);
    //查询购物车商品数量
    List<Cart> getCartProductCount(Integer userId);
    //购物车全选
    int selectAllProduct(Integer userId);
    //购物车取消全选
    int unselectAll(Integer userId);
    //查询已选中商品
    List<Cart> getSelectProduct(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);
}